name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Add nuget.org as nuget package source
      run: dotnet nuget add source https://api.nuget.org/v3/index.json --name nuget.org
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
